
import { TenseData, VocabularyCategory } from './types';

export const UI_STRINGS = {
  en: {
    appName: "TenseGenius",
    dashboard: "Learning Path",
    basics: "The Foundation",
    vocabulary: "Vocabulary",
    learn: "Explore",
    practice: "Practice",
    aiAssistant: "Panda Teacher",
    streak: "Streak",
    xp: "XP",
    unlockLevel: "Unlock",
    backToDashboard: "Back",
    nextLesson: "Next",
    askAi: "Ask Teacher Panda...",
    writeSentences: "Write sentences. Focus on Subject + Verb agreement!",
    submitPractice: "Analyze my English",
    basicsTitle: "Step 0: The Core",
    basicsSubtitle: "Mastering how the Subject (Who) controls the Verb (Action).",
    whatIsSentence: "Sentence Logic",
    sentenceExplanation: "A sentence is like a team. The Subject is the Captain, and the Verb is the Action. They must agree!",
    subject: "1. Subject (Ega)",
    subjectDesc: "The hero/boss of the sentence. (I, You, We, They, He, She, It, Tom)",
    verb: "2. Verb (Fe'l)",
    verbDesc: "The action. It changes shape based on the Subject. (Go vs Goes)",
    object: "3. Object (To'ldiruvchi)",
    objectDesc: "Receives the action. (English, Apple, School)",
    formula: "S + V + O Formula",
    agreement: "Subject-Verb Agreement (Tobelik)",
    agreementDesc: "If the Subject is singular (He/She/It), the Verb often changes!",
    switchLang: "O'zbekcha",
    timeline: "Timeline",
    structureTable: "The Formula Map",
    positive: "Positive (+)",
    negative: "Negative (-)",
    question: "Question (?)",
    shortAnswers: "Short Answers",
    examples: "Mastery Examples",
    examplesSub: "Real-world Subject-Verb connections.",
    mistakes: "Critical Pitfalls",
    mistakesSub: "Common mistakes in this tense.",
    finalTask: "Global Mastery Task",
    finalTaskPrompt: "Tell your life story using mixed tenses (120-180 words).",
    startJourney: "Start Journey",
    level: "Level",
    important: "Teacher's Tip:",
    comparison: "Comparison",
    comparisonSub: "Subtle differences.",
    vocabTitle: "Vocabulary",
    vocabSubtitle: "Bricks for your sentences.",
    writingVocab: "Writing Tools",
    searchVocab: "Search words...",
    wordInfo: "Detail",
    hideTranslation: "Hide Uzb",
    showTranslation: "Show Uzb",
    visualExample: "Complete Visual Example",
    who: "Who?",
    doWhat: "Do what?",
    what: "What?",
    svoHeading: "Basic Sentence Structure: S + V + O",
    svoSub: "Asosiy gap tuzilishi: Ega + Fe'l + To'ldiruvchi (S + V + O)",
    whatIsTense: "What is Tense?",
    tenseExplanation: "Tense tells us when an action happens. It shows if something happened in the past, is happening now, or will happen in the future.",
    pastLabel: "Past",
    presentLabel: "Present",
    futureLabel: "Future",
    alreadyHappened: "Already happened",
    happeningNow: "Happening now",
    willHappenLater: "Will happen later",
    actionFinished: "Action is finished",
    actionCurrent: "Action is current",
    actionPlanned: "Action is planned",
    aboutPlatform: "About the Platform",
    platformPurpose: "What does this site teach?",
    platformDesc: "TenseGenius is an AI-driven platform specifically designed to help students master the 16 English tenses through a structured multi-level system.",
    aboutDev: "About the Developer",
    devBio: "Sodiqjon Mukhtorov is a passionate young web developer specializing in creating intelligent educational tools.",
    telegramProfile: "Telegram profile",
    login: "Login",
    register: "Sign Up",
    fullName: "Full Name",
    username: "Username",
    phone: "Phone Number",
    password: "Password",
    confirmPassword: "Confirm Password",
    forgotPassword: "Forgot Password?",
    resetPassword: "Reset Password",
    loginBtn: "Enter",
    registerBtn: "Create Account",
    confirmed: "Confirmed!",
    logout: "Leave",
    userCode: "Your ID Code",
    adminPanel: "Admin Control",
    giftXp: "Gift XP",
    enterCode: "Enter User Code",
    amount: "XP Amount",
    send: "Send",
    usersList: "Registered Users"
  },
  uz: {
    appName: "TenseGenius",
    dashboard: "O'quv Yo'li",
    basics: "Asoslar",
    vocabulary: "Lug'at",
    learn: "O'rganish",
    practice: "Mashq",
    aiAssistant: "Panda Ustoz",
    streak: "Kun",
    xp: "XP",
    unlockLevel: "Ochish",
    backToDashboard: "Orqaga",
    nextLesson: "Keyingi",
    askAi: "Pandadan so'rash...",
    writeSentences: "Gaplar yozing. Ega va Fe'l moslashuviga (tobelikka) e'tibor bering!",
    submitPractice: "AI Tahlili",
    basicsTitle: "0-qadam: Poydevor",
    basicsSubtitle: "Ega (Kim) va Fe'l (Harakat) orasidagi tobelikni o'rganish.",
    whatIsSentence: "Gap mantiqi",
    sentenceExplanation: "Gap — bu jamoa kabidir. Ega — bu kapitan, Fe'l — harakat. Ular kelishishi shart!",
    subject: "1. Ega (Subject)",
    subjectDesc: "Gapning qahramoni/boshlig'i. Harakatni kim bajaryapti? (Men, Sen, U, Tom)",
    verb: "2. Fe'l (Verb)",
    verbDesc: "Harakat. U Egaga qarab shaklini o'zgartiradi. (Go vs Goes)",
    object: "3. To'ldiruvchi (Object)",
    objectDesc: "Harakat kimga/nimaga yo'naltirilgan? (Ingliz tili, Olma, Maktab)",
    formula: "S + V + O Formulalari",
    agreement: "Ega va Fe'l moslashuvi (Tobelik)",
    agreementDesc: "Agar Ega birlikda (He/She/It) bo'lsa, Fe'l shakli o'zgaradi!",
    switchLang: "English",
    timeline: "Vaqt chizig'i",
    structureTable: "Formula xaritasi",
    positive: "Tasdiq (+)",
    negative: "Inkor (-)",
    question: "So'roq (?)",
    shortAnswers: "Qisqa javoblar",
    examples: "Eng yaxshi misollar",
    examplesSub: "Ega va Fe'l bog'liqligini ko'ring.",
    mistakes: "Ehtiyot bo'ling!",
    mistakesSub: "Ushbu zamonda ko'p qilinadigan xatolar.",
    finalTask: "Global Imtihon",
    finalTaskPrompt: "Aralash zamonlar yordamida hikoya yozing (120-180 so'z).",
    startJourney: "Boshlash",
    level: "Daraja",
    important: "Ustoz Maslahati:",
    comparison: "Taqqoslash",
    comparisonSub: "Nozik farqlar.",
    vocabTitle: "Lug'at",
    vocabSubtitle: "Gaplaringiz uchun g'ishtlar.",
    writingVocab: "Yozuv qurollari",
    searchVocab: "Qidirish...",
    wordInfo: "Tahlil",
    hideTranslation: "Yopish",
    showTranslation: "Ko'rsatish",
    visualExample: "To'liq vizual misol",
    who: "Who?",
    doWhat: "Do what?",
    what: "What?",
    svoHeading: "Asosiy gap tuzilishi: S + V + O",
    svoSub: "Asosiy gap tuzilishi: Ega + Fe'l + To'ldiruvchi (S + V + O)",
    whatIsTense: "Zamon nima?",
    tenseExplanation: "Zamon — harakat QACHON sodir bo'lganini bildiradi.",
    pastLabel: "O'tgan",
    presentLabel: "Hozirgi",
    futureLabel: "Kelasi",
    alreadyHappened: "Tugagan harakat",
    happeningNow: "Hozir bo'lyapti",
    willHappenLater: "Keyin bo'ladi",
    actionFinished: "Harakat tugadi",
    actionCurrent: "Harakat hozirgi",
    actionPlanned: "Harakat rejalangan",
    aboutPlatform: "Platforma haqida",
    platformPurpose: "Ushbu sayt nimani o'rgatadi?",
    platformDesc: "TenseGenius - bu sun'iy intellektga asoslangan platforma.",
    aboutDev: "Dasturchi haqida",
    devBio: "Sodiqjon Mukhtorov - intellektual ta'lim vositalarini yaratishga qiziqqan yosh web-dasturchi.",
    telegramProfile: "Telegram profil",
    login: "Kirish",
    register: "Ro'yxatdan o'tish",
    fullName: "Foydalanuvchi ismi",
    username: "Foydalanuvchi nomi",
    phone: "Telefon raqam",
    password: "Parol",
    confirmPassword: "Parolni tasdiqlang",
    forgotPassword: "Parolni unutdingizmi?",
    resetPassword: "Parolni tiklash",
    loginBtn: "Kirish",
    registerBtn: "Ro'yxatdan o'tish",
    confirmed: "Tasdiqlandi!",
    logout: "Leave",
    userCode: "Sizning ID kodingiz",
    adminPanel: "Admin Panel",
    giftXp: "XP yuborish",
    enterCode: "Foydalanuvchi kodi",
    amount: "XP miqdori",
    send: "Yuborish",
    usersList: "Foydalanuvchilar ro'yxati"
  }
};

export const SVO_EXAMPLES = [
  { s: "She", v: "drinks", o: "water", full: "She drinks water." },
  { s: "We", v: "play", o: "football", full: "We play football." },
  { s: "The cat", v: "catches", o: "mice", full: "The cat catches mice." },
  { s: "They", v: "watch", o: "movies", full: "They watch movies." }
];

export const LEVELS = [
  { id: 1, name: "Level 1 – Beginner Tenses", tenses: ['pres-simple', 'pres-cont', 'past-simple', 'future-simple'] },
  { id: 2, name: "Level 2 – Intermediate Flow", tenses: ['pres-perf', 'pres-perf-cont', 'past-cont', 'future-cont'] },
  { id: 3, name: "Level 3 – Advanced Completion", tenses: ['past-perf', 'past-perf-cont', 'future-perf', 'future-perf-cont'] },
  { id: 4, name: "Level 4 – Expert Perspectives", tenses: ['fitp-simple', 'fitp-cont', 'fitp-perf', 'fitp-perf-cont'] },
];

export const TENSES_DATA: TenseData[] = [
  {
    id: 'pres-simple',
    levelId: 1,
    colorTheme: 'present',
    name: { en: "Present Simple", uz: "Oddiy hozirgi zamon" },
    description: { en: "Daily routines and general facts.", uz: "Kundalik odatlar va umumiy faktlar." },
    detailedExplanation: { en: "Used for things that happen regularly.", uz: "Muntazam sodir bo'ladigan ishlar uchun." },
    timeline: "Repeated actions (Every day, always).",
    whenToUse: { en: ["Habits", "Facts"], uz: ["Odatlar", "Faktlar"] },
    signalWords: ["always", "usually", "often"],
    commonMistakes: [{ wrong: "He play", correct: "He plays", note: { en: "Add 's' for he/she/it.", uz: "He/she/it uchun 's' qo'shing." } }],
    structure: {
      positive: { rows: [{ subject: "I/You/We/They", verb: "play", example: "I play" }, { subject: "He/She/It", verb: "plays", example: "He plays" }], formula: "S + V(s/es)" },
      negative: { rows: [{ subject: "He", helper: "doesn't", verb: "play", example: "He doesn't play" }], formula: "S + don't/doesn't + V" },
      question: { rows: [{ helper: "Does", subject: "she", verb: "play?", example: "Does she play?" }], formula: "Do/Does + S + V?" },
      shortAnswers: "Yes, I do / No, she doesn't"
    },
    examples: [
      { sentence: "I **drink** coffee every morning.", translation: "Men har tong qahva ichaman.", type: 'positive', note: { en: "Habit", uz: "Odat" } },
      { sentence: "He **doesn't like** apples.", translation: "U olmalarni yoqtirmaydi.", type: 'negative', note: { en: "Dislike", uz: "Yoqtirmaslik" } },
      { sentence: "**Do** you **play** football?", translation: "Siz futbol o'ynaysizmi?", type: 'question', note: { en: "Question", uz: "So'roq" } }
    ],
    practice: [
      { type: 'writing', question: "He ____ (work) in a bank.", answer: "works", hint: { en: "3rd person singular.", uz: "Uchinchi shaxs birlik." } },
      { type: 'choice', question: "They ____ football every Sunday.", answer: "play", options: ["play", "plays", "playing"], hint: { en: "Plural subject.", uz: "Ega ko'plikda." } },
      { type: 'writing', question: "I ____ (not/like) apples.", answer: "don't like", hint: { en: "Negative form for 'I'.", uz: "'I' uchun inkor shakli." } },
      { type: 'choice', question: "____ she speak English?", answer: "Does", options: ["Do", "Does", "Is"], hint: { en: "Helper for 'she'.", uz: "'She' uchun yordamchi fe'l." } },
      { type: 'writing', question: "The sun ____ (rise) in the east.", answer: "rises", hint: { en: "General fact.", uz: "Umumiy fakt." } },
      { type: 'choice', question: "We ____ to the gym usually.", answer: "go", options: ["go", "goes", "going"], hint: { en: "First person plural.", uz: "Birinchi shaxs ko'plik." } },
      { type: 'writing', question: "My father ____ (wash) his car every week.", answer: "washes", hint: { en: "Add -es after -sh.", uz: "-sh dan keyin -es qo'shiladi." } },
      { type: 'choice', question: "Cats ____ milk.", answer: "like", options: ["like", "likes", "liking"], hint: { en: "Plural animals.", uz: "Hayvonlar ko'plikda." } },
      { type: 'writing', question: "Where ____ you live?", answer: "do", hint: { en: "Question helper.", uz: "So'roq yordamchisi." } },
      { type: 'choice', question: "It ____ a lot in winter.", answer: "rains", options: ["rain", "rains", "raining"], hint: { en: "Third person singular.", uz: "Uchinchi shaxs birlik." } }
    ]
  },
  {
    id: 'pres-cont',
    levelId: 1,
    colorTheme: 'continuous',
    name: { en: "Present Continuous", uz: "Hozirgi davomli zamon" },
    description: { en: "Actions happening right now.", uz: "Ayni damda sodir bo'layotgan harakatlar." },
    detailedExplanation: { en: "Use am/is/are + verb-ing.", uz: "Hozir bo'layotgan ishlar uchun am/is/are + fe'l-ing ishlating." },
    timeline: "In progress now.",
    whenToUse: { en: ["Now"], uz: ["Hozir"] },
    signalWords: ["now", "at the moment"],
    commonMistakes: [{ wrong: "I playing", correct: "I am playing", note: { en: "Missing helper.", uz: "Yordamchi fe'l yo'q." } }],
    structure: {
      positive: { rows: [{ subject: "I", verb: "am playing", example: "I am playing" }], formula: "S + am/is/are + V-ing" },
      negative: { rows: [{ subject: "I", helper: "am not", verb: "playing", example: "I'm not playing" }], formula: "S + am/is/are + not + V-ing" },
      question: { rows: [{ helper: "Are", subject: "you", verb: "playing?", example: "Are you playing?" }], formula: "Am/Is/Are + S + V-ing?" },
      shortAnswers: "Yes, I am / No, we aren't"
    },
    examples: [
      { sentence: "I **am studying** English now.", translation: "Men hozir ingliz tili o'qiyapman.", type: 'positive', note: { en: "Current action", uz: "Hozirgi harakat" } },
      { sentence: "They **are not watching** TV.", translation: "Ular televizor ko'rishmayapti.", type: 'negative', note: { en: "Negative", uz: "Inkor" } },
      { sentence: "**Is** it **raining** outside?", translation: "Tashqarida yomg'ir yog'yaptimi?", type: 'question', note: { en: "Question", uz: "So'roq" } }
    ],
    practice: [
      { type: 'writing', question: "They ____ (listen) to music now.", answer: "are listening", hint: { en: "Plural subject.", uz: "Ko'plikdagi ega." } },
      { type: 'choice', question: "Look! The cat ____ on the tree.", answer: "is climbing", options: ["is climbing", "climbs", "climb"], hint: { en: "Action in progress.", uz: "Hozirgi harakat." } },
      { type: 'writing', question: "I ____ (study) for my exam at the moment.", answer: "am studying", hint: { en: "Helper for 'I'.", uz: "'I' uchun yordamchi." } },
      { type: 'choice', question: "____ you watching TV?", answer: "Are", options: ["Is", "Am", "Are"], hint: { en: "Helper for 'you'.", uz: "'You' uchun yordamchi." } },
      { type: 'writing', question: "She ____ (not/wear) a hat today.", answer: "is not wearing", hint: { en: "Negative continuous.", uz: "Davomli inkor." } },
      { type: 'choice', question: "We ____ dinner right now.", answer: "are having", options: ["have", "having", "are having"], hint: { en: "We + helper + ing.", uz: "We + yordamchi + ing." } },
      { type: 'writing', question: "Who ____ (sing) downstairs?", answer: "is singing", hint: { en: "Singular person.", uz: "Birlikdagi shaxs." } },
      { type: 'choice', question: "Wait! I ____ my shoes.", answer: "am putting on", options: ["put on", "am putting on", "is putting on"], hint: { en: "Current action.", uz: "Hozirgi harakat." } },
      { type: 'writing', question: "The children ____ (play) in the garden.", answer: "are playing", hint: { en: "Children (plural).", uz: "Bolalar (ko'plik)." } },
      { type: 'choice', question: "Listen! Somebody ____ the door.", answer: "is knocking", options: ["knocks", "is knocking", "knocking"], hint: { en: "Present progress.", uz: "Hozirgi davomiylik." } }
    ]
  },
  {
    id: 'past-simple',
    levelId: 1,
    colorTheme: 'past',
    name: { en: "Past Simple", uz: "Oddiy o'tgan zamon" },
    description: { en: "Finished actions in the past.", uz: "O'tmishda tugagan harakatlar." },
    detailedExplanation: { en: "Fe'lning 2-shakli (V2) yoki -ed qo'shimchasi ishlatiladi.", uz: "O'tmishda tugallangan harakatlar uchun ishlatiladi." },
    timeline: "Action finished yesterday.",
    whenToUse: { en: ["Completed tasks"], uz: ["Tugallangan ishlar"] },
    signalWords: ["yesterday", "ago", "last week"],
    commonMistakes: [{ wrong: "Did you went?", correct: "Did you go?", note: { en: "After 'did', use base verb.", uz: "'did'dan keyin asosiy fe'lni ishlating." } }],
    structure: {
      positive: { rows: [{ subject: "I/You/We/They", verb: "went", example: "I went" }, { subject: "He/She/It", verb: "played", example: "He played" }], formula: "S + V2/ed" },
      negative: { rows: [{ subject: "I", helper: "didn't", verb: "go", example: "I didn't go" }], formula: "S + didn't + V" },
      question: { rows: [{ helper: "Did", subject: "you", verb: "go?", example: "Did you go?" }], formula: "Did + S + V?" },
      shortAnswers: "Yes, I did / No, I didn't"
    },
    examples: [
      { sentence: "We **visited** Samarkand last year.", translation: "O'tgan yili Samarqandga bordik.", type: 'positive', note: { en: "Finished action", uz: "Tugagan ish" } },
      { sentence: "I **didn't see** him yesterday.", translation: "Kecha uni ko'rmadim.", type: 'negative', note: { en: "Negative", uz: "Inkor" } },
      { sentence: "**Did** you **call** me?", translation: "Menga qo'ng'iroq qildingmi?", type: 'question', note: { en: "Question", uz: "So'roq" } }
    ],
    practice: [
      { type: 'writing', question: "I ____ (see) a movie yesterday.", answer: "saw", hint: { en: "Irregular verb.", uz: "Noto'g'ri fe'l." } },
      { type: 'choice', question: "They ____ to London last month.", answer: "went", options: ["go", "goes", "went"], hint: { en: "Past of 'go'.", uz: "'Go' ning o'tgan shakli." } },
      { type: 'writing', question: "She ____ (not/visit) her aunt last week.", answer: "didn't visit", hint: { en: "Negative past.", uz: "O'tgan inkor." } },
      { type: 'choice', question: "____ you call me an hour ago?", answer: "Did", options: ["Do", "Does", "Did"], hint: { en: "Past helper.", uz: "O'tgan yordamchi." } },
      { type: 'writing', question: "We ____ (play) tennis two days ago.", answer: "played", hint: { en: "Regular verb.", uz: "To'g'ri fe'l." } },
      { type: 'choice', question: "I ____ my keys this morning.", answer: "lost", options: ["lose", "lost", "losing"], hint: { en: "Past of 'lose'.", uz: "'Lose' ning o'tgan shakli." } },
      { type: 'writing', question: "He ____ (arrive) at 8 PM.", answer: "arrived", hint: { en: "Regular -ed.", uz: "To'g'ri -ed." } },
      { type: 'choice', question: "We ____ dinner at a restaurant.", answer: "had", options: ["have", "has", "had"], hint: { en: "Past of 'have'.", uz: "'Have' ning o'tgan shakli." } },
      { type: 'writing', question: "They ____ (not/know) the answer.", answer: "didn't know", hint: { en: "Negative helper.", uz: "Inkor yordamchisi." } },
      { type: 'choice', question: "____ the movie good?", answer: "Was", options: ["Was", "Were", "Did"], hint: { en: "Be in past.", uz: "O'tgan 'be'." } }
    ]
  },
  {
    id: 'future-simple',
    levelId: 1,
    colorTheme: 'future',
    name: { en: "Future Simple", uz: "Oddiy kelasi zamon" },
    description: { en: "Predictions and sudden decisions.", uz: "Kelajak bashoratlari va to'satdan qarorlar." },
    detailedExplanation: { en: "Use 'will' + base verb.", uz: "Kelajakdagi ishlar uchun oddiy 'will' + fe'l." },
    timeline: "Action in the future.",
    whenToUse: { en: ["Predictions", "Promises"], uz: ["Bashoratlar", "Va'dalar"] },
    signalWords: ["tomorrow", "soon", "next year"],
    commonMistakes: [{ wrong: "I will to go", correct: "I will go", note: { en: "No 'to' after will.", uz: "Willdan keyin 'to' yo'q." } }],
    structure: {
      positive: { rows: [{ subject: "All", verb: "will go", example: "I will go" }], formula: "S + will + V" },
      negative: { rows: [{ subject: "All", helper: "won't", verb: "go", example: "I won't go" }], formula: "S + won't + V" },
      question: { rows: [{ helper: "Will", subject: "you", verb: "go?", example: "Will you go?" }], formula: "Will + S + V?" },
      shortAnswers: "Yes, I will / No, I won't"
    },
    examples: [
      { sentence: "I **will call** you later.", translation: "Sizga keyinroq qo'ng'iroq qilaman.", type: 'positive', note: { en: "Promise", uz: "Va'da" } },
      { sentence: "It **won't rain** tomorrow.", translation: "Ertaga yomg'ir yog'maydi.", type: 'negative', note: { en: "Prediction", uz: "Bashorat" } },
      { sentence: "**Will** you **help** me?", translation: "Menga yordam berasizmi?", type: 'question', note: { en: "Offer/Question", uz: "Taklif/So'roq" } }
    ],
    practice: [
      { type: 'writing', question: "It ____ (rain) tomorrow.", answer: "will rain", hint: { en: "Future prediction.", uz: "Kelajak bashorati." } },
      { type: 'choice', question: "I think they ____ the match.", answer: "will win", options: ["win", "wins", "will win"], hint: { en: "Prediction.", uz: "Bashorat." } },
      { type: 'writing', question: "I ____ (help) you with your bags.", answer: "will help", hint: { en: "Sudden offer.", uz: "To'satdan taklif." } },
      { type: 'choice', question: "Wait! I ____ the door for you.", answer: "will open", options: ["open", "will open", "opened"], hint: { en: "Instant decision.", uz: "Tezkor qaror." } },
      { type: 'writing', question: "They ____ (not/be) here on Monday.", answer: "won't be", hint: { en: "Negative future.", uz: "Kelasi inkor." } },
      { type: 'choice', question: "____ you marry me?", answer: "Will", options: ["Do", "Did", "Will"], hint: { en: "Question about future.", uz: "Kelajak haqida so'roq." } },
      { type: 'writing', question: "Next year ____ (be) better.", answer: "will be", hint: { en: "Future state.", uz: "Kelajakdagi holat." } },
      { type: 'choice', question: "I promise I ____ tell anyone.", answer: "won't", options: ["won't", "don't", "didn't"], hint: { en: "Future promise.", uz: "Kelasi va'da." } },
      { type: 'writing', question: "Maybe it ____ (snow) tonight.", answer: "will snow", hint: { en: "Prediction.", uz: "Bashorat." } },
      { type: 'choice', question: "We ____ probably go to France.", answer: "will", options: ["will", "are", "do"], hint: { en: "Future plan.", uz: "Kelajak rejasi." } }
    ]
  },
  {
    id: 'pres-perf',
    levelId: 2,
    colorTheme: 'perfect',
    name: { en: "Present Perfect", uz: "Hozirgi tugallangan zamon" },
    description: { en: "Past actions with results now.", uz: "Hozirgi natijasi bor o'tgan harakatlar." },
    detailedExplanation: { en: "Have/Has + V3. Focus is on the result or experience, not the time.", uz: "Have/Has + Fe'lning 3-shakli. Vaqt emas, natija muhim." },
    timeline: "Indefinite past connecting to present.",
    whenToUse: { en: ["Experiences", "Recent actions", "Change over time"], uz: ["Tajribalar", "Yaqinda bo'lgan ishlar", "Vaqt o'tishi bilan o'zgarishlar"] },
    signalWords: ["ever", "never", "yet", "already", "just", "since", "for"],
    commonMistakes: [{ wrong: "I have went", correct: "I have gone", note: { en: "Use V3.", uz: "V3 ishlating." } }],
    structure: {
      positive: { rows: [{ subject: "I/You/We/They", verb: "have gone", example: "I have gone" }, { subject: "He/She/It", verb: "has gone", example: "She has gone" }], formula: "S + have/has + V3" },
      negative: { rows: [{ subject: "She", helper: "hasn't", verb: "gone", example: "She hasn't gone" }], formula: "S + haven't/hasn't + V3" },
      question: { rows: [{ helper: "Have", subject: "you", verb: "gone?", example: "Have you gone?" }], formula: "Have/Has + S + V3?" },
      shortAnswers: "Yes, I have"
    },
    examples: [
      { sentence: "I **have seen** this movie before.", translation: "Men bu kinoni oldin ko'rganman.", type: 'positive', note: { en: "Experience", uz: "Tajriba" } },
      { sentence: "We **haven't eaten** lunch yet.", translation: "Biz hali tushlik qilmadik.", type: 'negative', note: { en: "Not finished yet", uz: "Hali tugallanmagan" } },
      { sentence: "**Have** you ever **been** to Samarkand?", translation: "Hech Samarqandda bo'lganmisiz?", type: 'question', note: { en: "Experience question", uz: "Tajriba so'rog'i" } }
    ],
    practice: [
      { type: 'writing', question: "She ____ (lose) her keys.", answer: "has lost", hint: { en: "Recent result.", uz: "Yaqindagi natija." } },
      { type: 'choice', question: "I ____ never seen a lion.", answer: "have", options: ["have", "has", "had"], hint: { en: "First person helper.", uz: "Birinchi shaxs yordamchisi." } },
      { type: 'writing', question: "We ____ ____ (finish) our homework.", answer: "have finished", hint: { en: "Completed action.", uz: "Tugallangan ish." } },
      { type: 'choice', question: "____ you ever visited Tashkent?", answer: "Have", options: ["Have", "Has", "Do"], hint: { en: "Question for 'you'.", uz: "'You' uchun so'roq." } },
      { type: 'writing', question: "He ____ (not/be) to Japan yet.", answer: "hasn't been", hint: { en: "Negative form.", uz: "Inkor shakli." } },
      { type: 'choice', question: "They ____ lived here for years.", answer: "have", options: ["have", "has", "had"], hint: { en: "Plural subject.", uz: "Ko'plikdagi ega." } },
      { type: 'writing', question: "I ____ ____ (buy) a new car.", answer: "have bought", hint: { en: "Past of 'buy' is 'bought'.", uz: "'Buy' ning o'tgan shakli 'bought'." } },
      { type: 'choice', question: "She has ____ her lunch already.", answer: "eaten", options: ["eat", "ate", "eaten"], hint: { en: "Use V3.", uz: "V3 ishlating." } },
      { type: 'writing', question: "____ she ____ (call) you today?", answer: "Has... called", hint: { en: "Third person question.", uz: "Uchinchi shaxs so'rog'i." } },
      { type: 'choice', question: "My parents ____ gone to the market.", answer: "have", options: ["have", "has", "is"], hint: { en: "Plural subject.", uz: "Ko'plikdagi ega." } }
    ]
  },
  {
    id: 'pres-perf-cont',
    levelId: 2,
    colorTheme: 'perfect',
    name: { en: "Present Perfect Continuous", uz: "Hozirgi tugallangan davomli" },
    description: { en: "Actions started in the past and still continuing.", uz: "O'tmishda boshlanib hali ham davom etayotgan ishlar." },
    detailedExplanation: { en: "Have/Has been + V-ing. Used to emphasize the duration of an activity.", uz: "Have/Has been + been + fe'l-ing. Harakatning davomiyligini ta'kidlash uchun." },
    timeline: "Started in past, continuing now, often emphasizing duration.",
    whenToUse: { en: ["Duration of action", "Recent activity with present effect"], uz: ["Harakatning davomiyligi", "Hozirgi natijasi bor yaqinda tugagan davomli ish"] },
    signalWords: ["for", "since", "all day", "how long"],
    commonMistakes: [{ wrong: "I have being", correct: "I have been", note: { en: "Use 'been'.", uz: "'been' ishlating." } }],
    structure: {
      positive: { rows: [{ subject: "I", verb: "have been playing", example: "I have been playing" }], formula: "S + have/has + been + V-ing" },
      negative: { rows: [{ subject: "He", helper: "hasn't been", verb: "playing", example: "He hasn't been playing" }], formula: "S + hasn't + been + V-ing" },
      question: { rows: [{ helper: "How long", subject: "have you", verb: "been playing?", example: "How long have you been playing?" }], formula: "How long + have/has + S + been + V-ing?" },
      shortAnswers: "Yes, I have"
    },
    examples: [
      { sentence: "I **have been waiting** for an hour.", translation: "Men bir soatdan beri kutyapman.", type: 'positive', note: { en: "Duration", uz: "Davomiylik" } },
      { sentence: "It **hasn't been raining** since morning.", translation: "Ertalabdan beri yomg'ir yog'mayapti.", type: 'negative', note: { en: "Negative", uz: "Inkor" } },
      { sentence: "**Have** you **been studying** all day?", translation: "Kun bo'yi dars qilyapsizmi?", type: 'question', note: { en: "Question", uz: "So'roq" } }
    ],
    practice: [
      { type: 'writing', question: "It ____ ____ ____ (rain) all day.", answer: "has been raining", hint: { en: "Continuous duration.", uz: "Davomiy vaqt." } },
      { type: 'choice', question: "They have been ____ for two hours.", answer: "working", options: ["work", "worked", "working"], hint: { en: "Use -ing form.", uz: "-ing shaklini ishlating." } },
      { type: 'writing', question: "I ____ ____ ____ (wait) for you.", answer: "have been waiting", hint: { en: "I + have + been + ing.", uz: "I + have + been + ing." } },
      { type: 'choice', question: "How long has she ____ studying?", answer: "been", options: ["being", "been", "be"], hint: { en: "Perfect continuous helper.", uz: "Tugallangan davomli yordamchisi." } },
      { type: 'writing', question: "We ____ ____ ____ (learn) English for years.", answer: "have been learning", hint: { en: "Duration marker 'for'.", uz: "Davomiylik 'for'." } }
    ]
  },
  {
    id: 'past-cont',
    levelId: 2,
    colorTheme: 'continuous',
    name: { en: "Past Continuous", uz: "O'tgan davomli zamon" },
    description: { en: "Actions in progress in the past.", uz: "O'tmishda ma'lum bir vaqtda davom etayotgan harakatlar." },
    detailedExplanation: { en: "Was/Were + V-ing. Often used with Past Simple to show an interrupted action.", uz: "O'tmishdagi ma'lum bir nuqtada davom etgan harakatlar. Ko'pincha Past Simple bilan ishlatiladi." },
    timeline: "Ongoing action at a specific past moment.",
    whenToUse: { en: ["Interrupted actions", "Background story", "Specific time in past"], uz: ["Bo'lingan harakatlar", "Hikoya foni", "O'tmishdagi aniq vaqt"] },
    signalWords: ["while", "when", "at that time", "at 5 o'clock"],
    commonMistakes: [{ wrong: "They was", correct: "They were", note: { en: "Use were for they.", uz: "They uchun were ishlating." } }],
    structure: {
      positive: { rows: [{ subject: "I/He/She/It", verb: "was playing", example: "I was playing" }, { subject: "You/We/They", verb: "were playing", example: "We were playing" }], formula: "S + was/were + V-ing" },
      negative: { rows: [{ subject: "You", helper: "weren't", verb: "playing", example: "You weren't playing" }], formula: "S + wasn't/weren't + V-ing" },
      question: { rows: [{ helper: "Were", subject: "you", verb: "sleeping?", example: "Were you sleeping?" }], formula: "Was/Were + S + V-ing?" },
      shortAnswers: "Yes, I was"
    },
    examples: [
      { sentence: "I **was reading** when you called.", translation: "Siz qo'ng'iroq qilganingizda men o'qiyotgan edim.", type: 'positive', note: { en: "Interrupted action", uz: "Bo'lingan harakat" } },
      { sentence: "They **were not working** at 5 PM.", translation: "Soat 5 da ular ishlashmayotgan edi.", type: 'negative', note: { en: "Negative at specific time", uz: "Aniq vaqtdagi inkor" } },
      { sentence: "**Was** she **crying** when you saw her?", translation: "Uni ko'rganingizda u yig'layotgan edimi?", type: 'question', note: { en: "Question in past progress", uz: "O'tgan davomiylik so'rog'i" } }
    ],
    practice: [
      { type: 'writing', question: "What ____ you ____ (do) at 8 PM?", answer: "were doing", hint: { en: "Past progress.", uz: "O'tgan davomiylik." } },
      { type: 'choice', question: "She ____ walking her dog when it rained.", answer: "was", options: ["was", "were", "is"], hint: { en: "Singular helper.", uz: "Birlik yordamchisi." } },
      { type: 'writing', question: "We ____ ____ (play) football at 10 AM.", answer: "were playing", hint: { en: "We + were + ing.", uz: "We + were + ing." } },
      { type: 'choice', question: "They ____ not sleeping when I arrived.", answer: "were", options: ["was", "were", "did"], hint: { en: "Plural helper.", uz: "Ko'plik yordamchisi." } },
      { type: 'writing', question: "____ it ____ (snow) last night?", answer: "Was snowing", hint: { en: "Question for 'it'.", uz: "'It' uchun so'roq." } }
    ]
  },
  {
    id: 'future-cont',
    levelId: 2,
    colorTheme: 'continuous',
    name: { en: "Future Continuous", uz: "Kelasi davomli zamon" },
    description: { en: "Actions in progress in the future.", uz: "Kelajakda ma'lum bir vaqtda davom etayotgan bo'ladigan harakatlar." },
    detailedExplanation: { en: "Will be + V-ing. Shows that an action will be happening at a specific time in the future.", uz: "Kelajakdagi ma'lum bir nuqtadagi davomiylik." },
    timeline: "Future progress at specific time.",
    whenToUse: { en: ["Specific future time", "Polite questions about plans"], uz: ["Aniq kelajak vaqti", "Rejalar haqida muloyim so'rovlar"] },
    signalWords: ["at this time tomorrow", "tomorrow morning", "all day next week"],
    commonMistakes: [{ wrong: "I will working", correct: "I will be working", note: { en: "Need 'be'.", uz: "'be' kerak." } }],
    structure: {
      positive: { rows: [{ subject: "All", verb: "will be flying", example: "I will be flying" }], formula: "S + will be + V-ing" },
      negative: { rows: [{ subject: "All", helper: "won't be", verb: "sleeping", example: "I won't be sleeping" }], formula: "S + won't be + V-ing" },
      question: { rows: [{ helper: "Will", subject: "you", verb: "be working?", example: "Will you be working?" }], formula: "Will + S + be + V-ing?" },
      shortAnswers: "Yes, I will"
    },
    examples: [
      { sentence: "I **will be lying** on the beach tomorrow morning.", translation: "Ertaga tongda plyajda yotgan bo'laman.", type: 'positive', note: { en: "Future moment", uz: "Kelajakdagi lahza" } },
      { sentence: "She **won't be sleeping** at 10 PM.", translation: "Soat 10 da u uxlamayotgan bo'ladi.", type: 'negative', note: { en: "Negative progress", uz: "Davomli inkor" } },
      { sentence: "**Will** you **be using** the car later?", translation: "Keyinroq mashinadan foydalanasizmi?", type: 'question', note: { en: "Polite inquiry", uz: "Muloyim so'rov" } }
    ],
    practice: [
      { type: 'writing', question: "I ____ ____ ____ (fly) to London tomorrow.", answer: "will be flying", hint: { en: "Ongoing future.", uz: "Davomli kelajak." } },
      { type: 'choice', question: "This time next week, we ____ on vacation.", answer: "will be", options: ["will be", "are", "have been"], hint: { en: "Future cont. helper.", uz: "Kelasi davomli yordamchisi." } }
    ]
  }
];

export const VOCABULARY_DATA: VocabularyCategory[] = [
  {
    id: 'advanced',
    name: { en: "Fundamental Lexicon", uz: "Asosiy terminlar" },
    items: [
      { word: "Fundamental", translation: "Asosiy, tub", definition: { en: "Forming a necessary base or core", uz: "Zarur poydevorni tashkil etuvchi" }, example: "A fundamental change in approach is needed.", type: "adjective" },
      { word: "Consequence", translation: "Oqibat, natija", definition: { en: "A result or effect of an action", uz: "Harakatning natijasi" }, example: "Every action has a consequence.", type: "noun" },
      { word: "Persuade", translation: "Ishontirmoq, ko'ndirmoq", definition: { en: "To convince someone", uz: "Kimnidir ishontirish" }, example: "I tried to persuade him to stay.", type: "verb" },
      { word: "Significant", translation: "Muhim, sezilarli", definition: { en: "Great or important", uz: "Muhim yoki katta" }, example: "A significant difference.", type: "adjective" },
      { word: "Ambiguous", translation: "Mavhum, noaniq", definition: { en: "Open to more than one interpretation", uz: "Bir nechta ma'noga ega bo'lish" }, example: "The law is ambiguous.", type: "adjective" },
      { word: "Contradict", translation: "Ziddiyatga bormoq", definition: { en: "Deny the truth of a statement", uz: "Fikrga qarshi chiqish" }, example: "The evidence contradicts his story.", type: "verb" },
      { word: "Appropriate", translation: "Muvofiq, mos", definition: { en: "Suitable or proper", uz: "Muvofiq yoki loyiq" }, example: "Appropriate behavior.", type: "adjective" },
      { word: "Analyze", translation: "Tahlil qilmoq", definition: { en: "Examine methodically", uz: "Uslubiy ravishda o'rganib chiqish" }, example: "We need to analyze the data.", type: "verb" },
      { word: "Diverse", translation: "Turli-tuman, xilma-xil", definition: { en: "Showing a great deal of variety", uz: "Xilma-xillikni ko'rsatish" }, example: "A diverse population.", type: "adjective" },
      { word: "Implement", translation: "Amalga oshirmoq, joriy etmoq", definition: { en: "Put into effect", uz: "Amalga oshirish" }, example: "Implement the plan.", type: "verb" },
      { word: "Obvious", translation: "Ayon, yaqqol", definition: { en: "Easily perceived or understood", uz: "Oson tushuniladigan" }, example: "It's obvious that he's lying.", type: "adjective" },
      { word: "Relevant", translation: "Aloqador, dolzarb", definition: { en: "Closely connected or appropriate", uz: "Tegishli yoki dolzarb" }, example: "Relevant information.", type: "adjective" },
      { word: "Vague", translation: "Xira, noaniq", definition: { en: "Of uncertain or unclear character", uz: "Aniq bo'lmagan" }, example: "A vague answer.", type: "adjective" },
      { word: "Sufficient", translation: "Yetarli", definition: { en: "Enough; adequate", uz: "Yetarli" }, example: "Sufficient funds.", type: "adjective" },
      { word: "Emphasis", translation: "Urg'u, e'tibor", definition: { en: "Special importance or value", uz: "Maxsus ahamiyat" }, example: "Emphasis on quality.", type: "noun" },
      { word: "Constraint", translation: "Cheklov", definition: { en: "A limitation or restriction", uz: "Cheklov yoki to'siq" }, example: "Time constraints.", type: "noun" },
      { word: "Consistent", translation: "Barqaror, izchil", definition: { en: "Acting or done in the same way", uz: "Bir xil tarzda bajariladigan" }, example: "Consistent results.", type: "adjective" },
      { word: "Hypothesis", translation: "Faraz", definition: { en: "A proposed explanation", uz: "Taklif qilingan tushuntirish" }, example: "A scientific hypothesis.", type: "noun" },
      { word: "Interpret", translation: "Talqin qilmoq", definition: { en: "Explain the meaning of", uz: "Ma'nosini tushuntirish" }, example: "Interpret the text.", type: "verb" },
      { word: "Objective", translation: "Maqsad / Xolis", definition: { en: "A goal or unbiased", uz: "Maqsad yoki betaraf" }, example: "Our main objective.", type: "noun/adjective" }
    ]
  }
];
